#! /bin/bash -x

check_prime() {
    number=$1
   flag=0
    i=2

    while [ $i -le $((number/2)) ]
    do
        if [ $(($number%$i)) -eq 0 ]
        then
            flag=1
        fi
        i=$(($i+1))
    done

 if [ $flag -eq 0 ]
        then echo $number
    fi
}
read -p "Enter A Number" num

for (( j=1; j<=$num; j++ ))
do
    check_prime $j
done

